# set these before building for a distribution!
# note that both must be bz2 archives.
[env]
index_path = "data/enwiktionary-20221220-pages-articles-multistream-index.txt.bz2"
dictionary_path = "data/enwiktionary-20221220-pages-articles-multistream.xml.bz2"
